disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - force_cast
  - identifier_name
  - line_length
  - function_body_length
  - nesting
  - type_name
  - valid_ibinspectable
  - implicit_getter
  - file_length
  - unused_enumerated
  - multiple_closures_with_trailing_closure
  - empty_enum_arguments
  - force_try
  #- trailing_newline
  #- opening_brace
  #- empty_count
  #- comma
  #- colon
  #- variable_name_min_length
  #- trailing_semicolon
  
  #- variable_name
  #- conditional_binding_cascade
  #- variable_name_max_length
  #- operator_whitespace
  #- control_statement
  #- legacy_constant
  #- return_arrow_whitespace
  #- statement_position
  #- type_body_length
  #- legacy_constructor
  #- valid_docs
  #- leading_whitespace
  #- shorthand_operator
  #- cyclomatic_complexity
  #- vertical_whitespace
  #- for_where
  #- syntactic_sugar
  #- vertical_parameter_alignment
  #- unused_closure_parameter
  #- mark
  #- unused_optional_binding
  #- private_over_fileprivate
  #- redundant_string_enum_value
  #- unneeded_break_in_switch
  #- redundant_optional_initialization
  #- function_parameter_count
  #- todo
  #- weak_delegate
  #- no_space_in_method_call
  #- large_tuple
  #- class_delegate_protocol
  #- trailing_comma
  #- void_return
  #- duplicate_imports
  #- unused_setter_value
  #- block_based_kvo
  #- empty_parentheses_with_trailing_closure
  #- redundant_discardable_let
  #- closing_brace
  #- redundant_void_return

#opt_in_rules: # some rules are only opt-in
#  - trailing_newline
#  - colon
#  - comma

included: # paths to include during linting. `--path` is ignored if present.
  - News

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - Project/R.generated.swift
  - Frameworks
  - Products